Add TLS support for trunk serve
ctron/trunk pull request #6
Opened 2023-11-16 16:29 UTC by lpotthast

Cherry-picked the change from @lukaselmer. Gonna verify it with a project I am working on. 
----

Use clippy, improve error handling

Improve tls example

Rename TLS options, improve path resolution

Move Rustls config parsing into rt.rs

# Conflicts:
#	CHANGELOG.md
#	Cargo.lock
#	Cargo.toml
#	Trunk.toml
#	src/config/models.rs
#	src/config/rt.rs
#	src/serve.rs

2023-11-16 16:41 UTC, lpotthast commented
@ctron Works good on my end!

2023-11-17 07:44 UTC, ctron requested changes
Thanks for the PR. I think it's good in general, some small things with the example which I would prefer to see fixed.

And the duplication issue (axum server start), but I think we'll figure this out.

2023-11-17 07:44 UTC, ctron commented on examples/yew-tls/README.md
> +# Trunk | Yew | ybc
I think the example is more about TLS?

2023-11-17 07:44 UTC, ctron commented on examples/yew-tls/self_signed_certs/cert.pem
> +-----BEGIN CERTIFICATE-----
The certificate seems to have expired 2022. I think for a certificate like this, having some expiry date in 2050 would work best :)

2023-11-17 07:44 UTC, ctron commented on src/serve.rs
> +        let mut http_server: Option<_> = None;
I am not a fan of this duplication … and I don't fully understand what's going on with the shutdown. I will try to see if we can improve this. Never worked with axum before, so I need to better understand this.

2023-11-17 07:44 UTC, ctron commented on src/serve.rs
> +        let mut http_server: Option<_> = None;
Just to be clear, I wouldn't consider this blocker. Just room for improvement.

2023-11-17 08:40 UTC, ctron commented on src/serve.rs
> +        let mut http_server: Option<_> = None;
Ok, I pushed some changes, consolidating the changes/differences into some function. Seems like the types are a bit complex to get them into a box or something.

I will go ahead and try this locally (non-TLS), maybe you can do the same (with TLS). It that works fine for both of us, then I think this part of resolved.

2023-11-17 08:50 UTC, ctron commented
Lints should also be fixed now.

2023-11-17 09:12 UTC, lpotthast commented
Aah, one thing is annoying. When performing a `build`, the `Trunk.toml` config is parsed and validated the same way as when running the `serve` command. In the nature of this change though: Users will probably generate their own certificates, with each user using its own certificate authority. In my project, the certs dir only contains a .gitkeep. Certs would not get commited. When running `build` inside a pipeline, no certs would be present then and the build aborts because the files referenced inside `Trunk.toml` could not be found... Quick pipeline-based fix would be
```
sed -i '/tls_cert_path/d' "./Trunk.toml"
sed -i '/tls_key_path/d' "./Trunk.toml"
```
but that should never be necessary. I think Trunk should actually ignore the tls configuration when not performing a serve. But that would require some conditional configuration evaluation, which is not currently there as it seems..

2023-11-17 09:17 UTC, ctron commented
But the certificates are only present in the `serve` configuration, does that really effect any other command?

2023-11-17 09:18 UTC, ctron commented
Ok, just tried it out. It's really causing an error.

2023-11-17 09:27 UTC, ctron commented
I think the issue comes from the fact that it tries to canonicalize the paths during reading the configuration. I am not sure that's a necessary step though. Just using the path as is should work fine.

2023-11-17 09:38 UTC, ctron commented
I noticed that the paths get actually canonicalized twice. First when parsing the configuration (in any case), second when starting the server (serve only). TBH, I am not convinced it is necessary in either case. But it gives a better error message when files are missing.

However, I think it's enough to do this when starting the `serve` command only. I made that change and it looks good to me. Maybe you can double check.

2023-11-20 07:23 UTC, ctron approved these changes
I think I fixed the remaining issues. Once the CI passes, I am going to merge it.

2023-11-20 07:29 UTC, merged